using UnityEngine;
using Dialogue.Data;
using System.Collections.Generic;
using System.IO;

[System.Serializable]
public class DialogueJsonData
{
    public string startNode;
    public NodeData[] nodes;
}

[System.Serializable]
public class NodeData
{
    public string id;
    public string speaker;
    public string action;
    public string type;
    public string eventName;
    public string trueNode;
    public string falseNode;
    public string text;
    public string next;
    public int minIntelligence;
    public int minCharisma;
    public int minStrength;
    public int maxIntelligence  = 11;
    public int maxCharisma = 11;
    public int maxStrength = 11;
    public string[] options;
}

namespace Dialogue.Core
{
    public class DialogueGraphLoader
    {
        public static DialogueGraph LoadGraph(string characterName)
        {
            string path = Path.Combine(Application.dataPath, "Dialogue", "Data", "NPC", characterName + ".json");
            string json = File.ReadAllText(path);
            DialogueJsonData data = JsonUtility.FromJson<DialogueJsonData>(json);

            Dictionary<string, Node> nodeMap = new();

            foreach (var node in data.nodes)
            {
                if (node.type == "line")
                {
                    var lineNode = ScriptableObject.CreateInstance<LineNode>();
                    nodeMap[node.id] = lineNode;
                }
                else if (node.type == "option")
                {
                    var optionNode = ScriptableObject.CreateInstance<OptionNode>();
                    nodeMap[node.id] = optionNode;
                }
                else if (node.type == "conditional")
                {
                    var conditionalNode = ScriptableObject.CreateInstance<ConditionalNode>();
                    nodeMap[node.id] = conditionalNode;
                }
            }

            foreach (var node in data.nodes)
            {
                if (node.type == "line")
                {
                    LineNode line = (LineNode)nodeMap[node.id];
                    line.LineText = node.text;
                    line.MinimumIntelligence = node.minIntelligence;
                    line.MinimumCharisma = node.minCharisma;
                    line.MinimumStrength = node.minStrength;
                    line.MaximumIntelligence = node.maxIntelligence;
                    line.MaximumCharisma = node.maxCharisma;
                    line.MaximumStrength = node.maxStrength;
                    line.Action = node.action;
                    line.Speaker = node.speaker == "player" ? SpeakerType.Player : SpeakerType.Npc;
                    if (node.next != null && nodeMap.ContainsKey(node.next))
                    {
                        line.NextNode = nodeMap[node.next];
                    }
                }
                else if (node.type == "option")
                {
                    OptionNode option = (OptionNode)nodeMap[node.id];
                    List<Node> nodeOptions = new();
                    foreach (var opt in node.options)
                    {
                        nodeOptions.Add(nodeMap[opt]);
                    }
                    option.Options = nodeOptions;
                }
                else if (node.type == "conditional")
                {
                    ConditionalNode cond = (ConditionalNode)nodeMap[node.id];
                    cond.EventName = node.eventName;
                    if (node.trueNode != null && nodeMap.ContainsKey(node.trueNode))
                    {
                        cond.ConditionMetNode = nodeMap[node.trueNode];
                    }
                    if (node.falseNode != null && nodeMap.ContainsKey(node.falseNode))
                    {
                        cond.ConditionNotMetNode = nodeMap[node.falseNode];
                    }
                }
            }

            DialogueGraph dialogueGraph = new DialogueGraph(nodeMap[data.startNode]);
            return dialogueGraph;
        }


/*THIS CODE BELOW IS GENERATED BY AN LLM FOR TESTING PURPOSES*/
        public static void PrintGraph(DialogueGraph graph)
        {
            Debug.Log("=== Dialogue Graph ===");
            PrintNode(graph.StartNode, 0, new HashSet<Node>());
            Debug.Log("=== End Graph ===");
        }

        private static void PrintNode(Node node, int depth, HashSet<Node> visited)
        {
            if (node == null || visited.Contains(node))
                return;

            visited.Add(node);
            string indent = new string(' ', depth * 2);

            if (node is LineNode line)
            {
                Debug.Log($"{indent}[Line] \"{line.LineText}\" (minInt: {line.MinimumIntelligence})");
                PrintNode(line.NextNode, depth + 1, visited);
            }
            else if (node is OptionNode option)
            {
                Debug.Log($"{indent}[Option] {option.Options.Count} choices:");
                for (int i = 0; i < option.Options.Count; i++)
                {
                    Debug.Log($"{indent}  [{i}]:");
                    PrintNode(option.Options[i], depth + 2, visited);
                }
            }
            else if (node is ConditionalNode cond)
            {
                Debug.Log($"{indent}[Conditional] event: \"{cond.EventName}\"");
                Debug.Log($"{indent}  true:");
                PrintNode(cond.ConditionMetNode, depth + 2, visited);
                Debug.Log($"{indent}  false:");
                PrintNode(cond.ConditionNotMetNode, depth + 2, visited);
            }
        }
    }
}