using UnityEngine;
using Dialogue.Data;
using System.Collections.Generic;

/*
DISCLAIMER: THIS FILE WAS GENERATED BY AN AI LANGUAGE MODEL (CHATGPT) FOR TESTING PURPOSES.
*/

namespace Dialogue.Core
{
    public class DialogueTest : MonoBehaviour
    {
        private DialogueRunner runner;

        void Start()
        {
            runner = gameObject.AddComponent<DialogueRunner>();
            
            // Subscribe to events
            runner.DialogueStartAction += () => Debug.Log("=== DIALOGUE STARTED ===");
            runner.LineNodeAction += (text) => Debug.Log($"LINE: {text}");
            runner.OptionNodeAction += (options) => {
                Debug.Log("OPTIONS:");
                for (int i = 0; i < options.Count; i++)
                    Debug.Log($"  [{i}] {options[i]}");
            };
            runner.DialogueEndAction += () => Debug.Log("=== DIALOGUE ENDED ===");

            // Run tests
            TestBasicDialogue();
        }

        void TestBasicDialogue()
        {
            Debug.Log("--- Test: Basic Dialogue Flow ---");
            
            // Create nodes
            var line1 = ScriptableObject.CreateInstance<LineNode>();
            var line2 = ScriptableObject.CreateInstance<LineNode>();
            var line3 = ScriptableObject.CreateInstance<LineNode>();

            // Use reflection to set private fields (for testing only)
            SetPrivateField(line1, "lineText", "Hello traveler!");
            SetPrivateField(line1, "nextNode", line2);
            
            SetPrivateField(line2, "lineText", "Welcome to the village.");
            SetPrivateField(line2, "nextNode", line3);
            
            SetPrivateField(line3, "lineText", "Safe travels!");
            SetPrivateField(line3, "nextNode", null);

            // Create graph
            var graph = new DialogueGraph(line1);

            // Set graph on runner (use reflection since it's private)
            SetPrivateField(runner, "dialogueGraph", graph);

            // Test the flow
            runner.BeginDialogue();
            runner.ProccessNode();  // "Hello traveler!"
            runner.Next();          // "Welcome to the village."
            runner.Next();          // "Safe travels!"
            runner.Next();          // Should end dialogue
        }

        void Update()
        {
            // Manual testing: Space to advance, 1/2/3 for options
            if (Input.GetKeyDown(KeyCode.Space))
                runner.Next();
            if (Input.GetKeyDown(KeyCode.Alpha1))
                runner.SelectOptions(0);
            if (Input.GetKeyDown(KeyCode.Alpha2))
                runner.SelectOptions(1);
        }

        // Helper to set private fields for testing
        private void SetPrivateField(object obj, string fieldName, object value)
        {
            var field = obj.GetType().GetField(fieldName, 
                System.Reflection.BindingFlags.NonPublic | 
                System.Reflection.BindingFlags.Instance);
            field?.SetValue(obj, value);
        }
    }
}